version: "2"
run:
  tests: false
  timeout: 5m
  concurrency: 4
  modules-download-mode: readonly
  allow-parallel-runners: false
  skip-dirs-use-default: true
output:
  formats:
    tab:
      path: stdout
  sort-order:
    - file
    - linter
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - predeclared
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
  disable:
    - contextcheck
    - exhaustive
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - gosec
    - inamedparam
    - ireturn
    - interfacebloat
    - lll
    - gomoddirectives
    - mnd
    - musttag
    - nilerr
    - nilnil
    - nlreturn
    - nonamedreturns
    - prealloc
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
    - whitespace
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        discouraged-packages:
          files:
            - "$all"
          deny:
            - pkg: "github.com/golang/protobuf"
              desc: "Use google.golang.org/protobuf instead"
            - pkg: "github.com/satori/go.uuid"
              desc: "Use github.com/google/uuid instead"
            - pkg: "math/rand$"
              desc: "Use math/rand/v2 instead (for non-test files)"
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 20
    gosec:
      excludes:
        - G115
        - G306
        - G402
        - G404
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      rules:
        - name: argument-limit
          arguments:
            - 5
        - name: atomic
        - name: banned-characters
          arguments:
            - ยง
            - ั
        - name: bare-return
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: call-to-gc
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: context-keys-type
        - name: datarace
        - name: defer
          arguments:
            - - call-chain
              - method-call
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
          arguments:
            - preserveScope
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: function-result-limit
          arguments:
            - 3
        - name: get-return
        - name: identical-branches
        - name: if-return
        - name: import-shadowing
        - name: increment-decrement
        - name: indent-error-flow
          arguments:
            - preserveScope
        - name: max-control-nesting
          arguments:
            - 5
        - name: range-val-address
        - name: range-val-in-closure
        - name: redefines-builtin-id
        - name: redundant-import-alias
        - name: string-of-int
        - name: superfluous-else
          arguments:
            - preserveScope
        - name: time-equal
        - name: time-naming
        - name: unchecked-type-assertion
          arguments:
            - acceptIgnoredAssertionResult: true
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
            - fmt.Fprint
            - fmt.Fprintln
            - fmt.Fprintf
            - strings.Builder.WriteString
            - strings.Builder.WriteRune
            - strings.Builder.Write
            - bytes.Builder.WriteString
            - bytes.Builder.WriteRune
            - bytes.Builder.Write
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
        - name: use-any
        - name: var-declaration
        - name: waitgroup-by-value

issues:
  max-same-issues: 50
  max-issues-per-linter: 0
  new: false
