# Production Environment Configuration
server:
  http: ":8080"
  # https: ":8443"
  # cert_file: "/etc/ssl/certs/server.crt"
  # key_file: "/etc/ssl/private/server.key"
  
  read_timeout: "30s"
  read_header_timeout: "10s"
  idle_timeout: "300s"
  
  enable_health_endpoint: true
  health_path: "/health"
  enable_default_metrics: true
  metrics_path: "/metrics"
  
  enable_request_size_limits: true
  max_request_body_size: 10485760     # 10MB in production
  max_json_body_size: 1048576         # 1MB
  max_file_upload_size: 5242880       # 5MB
  
  send_error_to_client: false

rate_limit:
  enabled: true
  requests_per_interval: 100
  interval: "1m"
  burst_size: 50
  status_code: 429
  exclude_paths:
    - "/health"
    - "/metrics"

filter:
  blocked_user_agents_regex:
    - ".*[Bb]ot.*"
    - ".*[Ss]craper.*"
    - ".*[Cc]rawler.*"
  exclude_paths:
    - "/health"
    - "/metrics"

security:
  enabled: true
  content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'"
  x_frame_options: "DENY"
  x_content_type_options: "nosniff"
  strict_transport_security: "max-age=31536000; includeSubDomains"
  referrer_policy: "strict-origin-when-cross-origin"

cache:
  enabled: true
  cache_control: "public, max-age=3600"
  exclude_paths:
    - "/api/*"
    - "/health"
    - "/metrics"

compression:
  enabled: true
  level: 6
  min_size: 1024
  types:
    - "text/html"
    - "text/css"
    - "application/javascript"
    - "application/json"
    - "text/plain"

logging:
  disable_request_logging: false
  no_log_client_errors: true  # Don't log client errors in production
  log_fields:
    - "method"
    - "url" 
    - "status"
    - "duration_ms"
    - "ip"

cors:
  enabled: true
  allow_origins:
    - "https://yourdomain.com"
    - "https://www.yourdomain.com"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Content-Type"
    - "Authorization"
  max_age: 86400
